name: Sanity
on: [push]
jobs:
  Sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m venv .venv
      - run: . .venv/bin/activate
      - run: ls -lah
      - run: pwd
      - run: sudo apt-get install -y libleptonica-dev
      - run: sudo apt-get install -y libtesseract-dev 
      - run: .venv/bin/python setup.py install
      - run: .venv/bin/python setup.py test