name: Sanity
on: [push]
jobs:
  Sanity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - run: >-
          sudo apt-get install -y
          libleptonica-dev
          tesseract-ocr-all
          libtesseract-dev
      - run: python3 -m venv .venv
      - run: .venv/bin/python -m pip install wheel
      - run: .venv/bin/python setup.py install
      - run: >-
          .venv/bin/python
          setup.py test
          --pytest-args "--junit-xml junit-report-${{ matrix.python-version}}.xml"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit-report-*.xml
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >-
          sudo apt-get install -y
          libleptonica-dev
          tesseract-ocr-all
          libtesseract-dev
      - run: python3 -m venv .venv
      - run: .venv/bin/python -m pip install wheel
      - run: .venv/bin/python setup.py lint

  Sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >-
          sudo apt-get install -y
          libleptonica-dev
          tesseract-ocr-all
          libtesseract-dev
          dvipng
      - run: python3 -m venv .venv
      - run: .venv/bin/python -m pip install wheel
      - run: .venv/bin/python setup.py install
      - run: .venv/bin/python setup.py apidoc
      - run: .venv/bin/python setup.py build_sphinx
      - name: Publish Docs to Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build/sphinx/html

  CondaBuild:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # exclude:
        #   # opencv is broken in this version
        #   - { os: ubuntu-latest, python-version: 3.9 }
        #   - { os: macos-latest, python-version: 3.9 }
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: s-weigand/setup-conda@v1
        with:
          conda-channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - run: conda create --name cleanx-build
      - run: conda run -n cleanx-build python setup.py bdist_egg
      - run: conda run -n cleanx-build python setup.py genconda
        # conda-build installation and the build cannot be in an
        # environment
      - run: conda install conda-build
      - run: conda build -c conda-forge ./conda-pkg/
      - run: conda install -n cleanx-build --use-local cleanx
      - run: conda install -n cleanx-build pytest pycodestyle
      - run: conda info
      - run: conda list -n cleanx-build
      - run: >-
          conda run -n cleanx-build
          python
          ./setup.py test
          --pytest-args
          "--junit-xml conda-${{ matrix.os }}-${{ matrix.python-version }}junit-report.xml"
