name: Release

on:
  push:
    tags:
      - v*

jobs:
  tagged-release:
    if: ${{ github.repository == 'drcandacemakedamoore/cleanX' }}
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        # Unfortunately, wheel will try to do setup.py install to
        # build a wheel... and we need this stuff to be able to build
        # for CPython.
      - run: >-
          sudo apt-get install -y libleptonica-dev tesseract-ocr-all
          libtesseract-dev
          python3-opencv
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: python3.8 -m venv .venv
      - run: .venv/bin/python -m pip install wheel twine
      - run: .venv/bin/python setup.py bdist_wheel
      - run: .venv/bin/python setup.py bdist_egg
      - run: >-
          TWINE_USERNAME=__token__
          TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }}
          .venv/bin/python -m twine upload --skip-existing ./dist/*

      - uses: s-weigand/setup-conda@v1
        with:
          conda-channels: conda-forge
      - run: conda install conda-build anaconda-client conda-verify
      - run: .venv/bin/python setup.py genconda -t 3.7
      - run: rm -rf ./build ./dist ./*.egg-info ./.eggs
      - run: conda build -c conda-forge --output-folder ./dist ./conda-pkg/
      - run: conda convert -p osx-64 -o ./dist ./dist/linux-64/*py37_0.tar.bz2
      - run: conda convert -p win-64 -o ./dist ./dist/linux-64/*py37_0.tar.bz2
      - run: >
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label main ./dist/linux-64/*py37_0.tar.bz2
      - run: >
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label main ./dist/osx-64/*py37_0.tar.bz2
      - run: >
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label main ./dist/win-64/*py37_0.tar.bz2
      - run: .venv/bin/python setup.py genconda -t 3.8
      - run: conda build -c conda-forge --output-folder ./dist ./conda-pkg/
      - run: conda convert -p osx-64 -o ./dist ./dist/linux-64/*.tar.bz2
      - run: conda convert -p win-64 -o ./dist ./dist/linux-64/*.tar.bz2
      - run: >
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label main ./dist/linux-64/*py38_0.tar.bz2
      - run: >
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label main ./dist/osx-64/*py38_0.tar.bz2
      - run: >
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label main ./dist/win-64/*py38_0.tar.bz2

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/linux-64/cleanx-*.tar.bz2
            ./dist/osx-64/cleanx-*.tar.bz2
            ./dist/win-64/cleanx-*.tar.bz2
            ./dist/*.whl
            ./dist/*.egg
